ci: add web job to workflow

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -225,3 +225,58 @@ jobs:
       - name: "E2E Tests"
         working-directory: tests
         run: flutter test ./integration_test/firebase_ui_test.dart -d macos --dart-define=CI=true
+  web:
+    runs-on: macos-latest
+    timeout-minutes: 15
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
+        name: Install Node.js 20
+        with:
+          node-version: '20'
+      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+      - uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
+        with:
+          channel: 'stable'
+          cache: true
+      - uses: bluefireteam/melos-action@720a109b686f61979b4f9f0d14f582ab1637647e
+        with:
+          run-bootstrap: false
+          melos-version: "3.0.1"
+      - name: "Bootstrap package"
+        run: melos bootstrap --scope tests
+      - name: 'Install Tools'
+        run: |
+          sudo npm i -g firebase-tools
+      - name: Cache Firebase Emulator
+        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
+        with:
+          path: ~/.cache/firebase/emulators
+          key: firebase-emulators-v1-${{ github.run_id }}
+          restore-keys: firebase-emulators-v1
+      - name: Start Firebase Emulator & proxy
+        run: |
+          sudo chown -R 501:20 "/Users/runner/.npm"
+          cd functions/
+          npm i
+          npm run build
+          ../scripts/start-firebase-emulator.sh
+      - name: 'E2E Tests'
+        working-directory: tests
+        # Web devices are not supported for the `flutter test` command yet. As a
+        # workaround we can use the `flutter drive` command. Tracking issue:
+        # https://github.com/flutter/flutter/issues/66264
+        run: |
+          chromedriver --port=4444 --trace-buffer-size=100000 &
+          flutter drive --target=./integration_test/firebase_ui_test.dart --driver=./test_driver/integration_test.dart -d chrome --dart-define=CI=true | tee output.log
+          # We have to check the output for failed tests matching the string "[E]"
+          output=$(<output.log)
+          if [[ "$output" =~ \[E\] ]]; then
+          # You will see "All tests passed." in the logs even when tests failed.
+          echo "All tests did not pass. Please check the logs for more information."
+          exit 1
+          fi
+        shell: bash
